### ISSUE TITLE
#5 Beta release - Use SWH API's save endpoint 

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/swMATH4EOSC#5]
**Describe the issue**

**Comment by Shirazos7** [comment]
i added a Summary regarding to this Issue 
it includes only one example of many 
I used it and described the steps just to give you an idea about how it works 
in the following markdown file you will see the links and the set of Data which can give you an idea about it. 
i would really appreciate your notes and advices to improve my work. 

[SWH API's Save Endpoint.md](https://github.com/MaRDI4NFDI/swMATH4EOSC/files/11623134/SWH.API.s.Save.Endpoint.md)

**Comment by Mazztok45** [comment]
We could save the SageMath software source code using the save code now endpoint of the SWH API.
