### ISSUE TITLE
#6 Beta release - Use SWH API's webhook endpoint

### ISSUE THREAD

**Issue by Mazztok45** [MaRDI4NFDI/swMATH4EOSC#6]
**Describe the issue**

**Comment by Shirazos7** [comment]
I hope this documentation will be helpful 
 i will be thankful for Any notes and advices  
 
[SWH Webhook endpoint.md](https://github.com/MaRDI4NFDI/swMATH4EOSC/files/11625769/SWH.Webhook.endpoint.md)

**Comment by Mazztok45** [comment]
We could use the webhook to archive this project.
